# This file was generated by GoReleaser. DO NOT EDIT.
cask "okf" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "fef958317c8c498374c3870d3adbe039cad6db2d6aa1ceb45c13ee1e759a0e41"
      url "https://github.com/okfcli/okf/releases/download/v#{version}/okf_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/okfcli/okf/"
    end
    on_intel do
      sha256 "a2430d6f89bdeb270326231a42a53d6dc3e48d49e58c098d77a7cc0c3d498a96"
      url "https://github.com/okfcli/okf/releases/download/v#{version}/okf_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/okfcli/okf/"
    end
  end
  on_linux do
    on_arm do
      sha256 "7e09188172d55fb856af915c1dda553e4976f4ab1d0820aebfa25768f31f6ae9"
      url "https://github.com/okfcli/okf/releases/download/v#{version}/okf_#{version}_linux_arm64.tar.gz",
        verified: "github.com/okfcli/okf/"
    end
    on_intel do
      sha256 "287b666f13cfb1507fddacc7202dce81de722ec1ffde81845b8ac3f16626d531"
      url "https://github.com/okfcli/okf/releases/download/v#{version}/okf_#{version}_linux_amd64.tar.gz",
        verified: "github.com/okfcli/okf/"
    end
  end

  name "okf"
  desc "Go CLI toolkit for the Open Knowledge Format (OKF), agentic-first and JSON-native"
  homepage "https://github.com/okfcli/okf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "okf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/okf"]
    end
  end

  # No zap stanza required
end
