# This file was generated by GoReleaser. DO NOT EDIT.
cask "okf" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "7665632742a2ba5e9f9833fdd318ae9778ae8089dbe8c2b0a3bfe3c56248260e"
      url "https://github.com/okfcli/okf/releases/download/v#{version}/okf_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/okfcli/okf/"
    end
    on_intel do
      sha256 "a927774b22390c2f5b9852a823f453a2d672040309b561a3a33a59e123d8f5b2"
      url "https://github.com/okfcli/okf/releases/download/v#{version}/okf_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/okfcli/okf/"
    end
  end
  on_linux do
    on_arm do
      sha256 "9be0f188be43dd80009d5f45132763415d2cd0312a98309bcaf7e25a8a236a41"
      url "https://github.com/okfcli/okf/releases/download/v#{version}/okf_#{version}_linux_arm64.tar.gz",
        verified: "github.com/okfcli/okf/"
    end
    on_intel do
      sha256 "fa6a2fbde05204c4eaf91123daac87353e9b42831cd426bbd9a1fda75dc805e4"
      url "https://github.com/okfcli/okf/releases/download/v#{version}/okf_#{version}_linux_amd64.tar.gz",
        verified: "github.com/okfcli/okf/"
    end
  end

  name "okf"
  desc "Go CLI toolkit for the Open Knowledge Format (OKF), agentic-first and JSON-native"
  homepage "https://github.com/okfcli/okf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "okf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/okf"]
    end
  end

  # No zap stanza required
end
